# Generated by Django 5.2.11 on 2026-02-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_uuid_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='code',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='code_hash',
            field=models.CharField(default='', max_length=255),
        ),
    ]
