# Generated by Django 5.2.11 on 2026-02-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
