# Generated by Django 5.2.11 on 2026-02-21 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_uuid_usersession'),
        ('tokens', '0002_refreshtoken_ip_address_refreshtoken_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimetoken',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='family_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_tokens', to='tokens.refreshtoken'),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='accounts.usersession'),
        ),
    ]
