# Generated by Django 5.2.16 on 2026-07-14 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('registration', 'Registration'), ('verification', 'Verification'), ('login_success', 'Login success'), ('login_failure', 'Login failure'), ('refresh_success', 'Refresh success'), ('refresh_failure', 'Refresh failure'), ('refresh_token_reuse', 'Refresh-token reuse'), ('logout', 'Logout'), ('logout_all', 'Logout all'), ('password_change', 'Password change'), ('password_reset', 'Password reset'), ('mfa_enrollment', 'MFA enrollment'), ('mfa_removal', 'MFA removal'), ('recovery_code_usage', 'Recovery-code usage'), ('session_revocation', 'Session revocation'), ('account_lock', 'Account lock'), ('account_suspension', 'Account suspension'), ('role_change', 'Role change'), ('permission_change', 'Permission change'), ('oauth_client_created', 'OAuth client created'), ('oauth_client_updated', 'OAuth client updated'), ('oauth_client_deleted', 'OAuth client deleted'), ('signing_key_change', 'Signing-key change'), ('email_submission', 'Email submission'), ('email_bounce', 'Email bounce'), ('email_complaint', 'Email complaint'), ('admin_action', 'Administrative action')], db_index=True, max_length=64)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], db_index=True, max_length=16)),
                ('actor_type', models.CharField(default='anonymous', max_length=32)),
                ('actor_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='audit_audit_event_t_14e051_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__59bbff_idx')],
            },
        ),
    ]
